### ISSUE TITLE
Organization of scripts by build numbers possible?

### ISSUE THREAD

**Issue by git4t** [rakker91/dbdeploy.net#1]
Hi, 

Does your tool provide any support for organizing the scripts inside the Scripts\Deployed Scripts folder based on build numbers? 

Scripts\Deployed Scripts 
        v.1.0.0.0 
              1.script.sql
        v.2.0.0.0 
              1.script.sql 
              2.script.sql 

etc..? 

If the above structure is supported by your tool, does the 1.script.sql file create a conflict as 'it's already installed'? even though it is separated out inside the two different folders? 

thanks.

**Comment by rakker91** [comment]
Scripts will be discovered through any number of folders, but the constraint to have each number be unique remains, so with the above example, 1 script.sql would collide, even though they're in different directories.

The reason why its that way is for ordering.  All scripts must be run in a particular order.  Currently the system doesn't understand the numbering of folders, simply because people group their folders in different ways.  For example, you're using release version, but many people use sprint numbers.

That'd be an interesting feature to add, though, but would require some mechanism to tell it how to interpret and order the script directories.

**Comment by git4t** [comment]
Ok. thanks for the prompt response.
