### ISSUE TITLE
How to maintain numbering when multiple people are working

### ISSUE THREAD

**Issue by git4t** [rakker91/dbdeploy.net#2]
Hi, 

How do we maintain the numbering if more than one person is working on the project. 

Meaning, if two people are working on the project, it is possible, they both can tend to name the script as 1.<script_name_xyz>.sql OR 
1.<script_name_abc>.sql

Is there any constraint or requirement that the numbers should not collide?

**Comment by rakker91** [comment]
Coordination is important when working with multiple developers.  Usually, teams will "claim" numbers in some kind of chat system (skype group, slack, flowdock, etc.), which works really well.  Order is often very important, so all scripts are run in order.  If scripts collide, a warning message will be given, letting you rename the script with a different number.

There's also a script list, that makes knowing what numbers have been reserved, but if you're working in separate branches, which is quite common, that's less helpful, since its not aware of what happens in other branches.

**Comment by git4t** [comment]
Ok. thanks for the prompt response.
